; FIND THE LARGEST NO. FROM AN UNORDERED ARRAY OF 5,8 BIT NUMBERS STORED SEQUENTIALLY IN THE MEMORY LOCATION STARTING AT OFFSET 0500H IN THE SEGMENT 2000H  

 MOV CX,04H  
 MOV AX,2000H
 MOV DS,AX    
 
 MOV SI,0500H
 MOV AL,[SI]
 BACK:INC SI
 CMP AL,[SI]   ;AL-SI
 JNC NEXT   
 MOV AL,[SI]
 NEXT:LOOP BACK
 HLT
 